"""remove type value

Revision ID: 112d976665c7
Revises: 293cffa1ae2b
Create Date: 2024-05-28 20:13:35.207770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112d976665c7'
down_revision = '293cffa1ae2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actuator', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=80), nullable=False))

    with op.batch_alter_table('actuator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
